apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-readonly-pv
spec:
  storageClassName: faster 
  # if you are not using ssd then just use ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: my-test-disk
    fsType: ext4 
    # see if you want to use ssd on google cloud, if you do then use storageClass and rid fsType.

    